version: "3"

services:
  todo_app:
    build:
      context: .
      target: debug
    ports:
      - 5000:80
    volumes:
      - type: bind
        source: .
        target: /app/todo_app
    env_file:
      - .env

